server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: backlog-service
          uri: lb://backlog-service
          predicates:
            - Path=/backlog/**
        - id: project-service
          uri: lb://project-service
          predicates:
              - Path=/project/**
        - id: projecttask-service
          uri: lb://projecttask-service
          predicates:
              - Path=/task/**
